# Configure your servers for Azumatt's FastLink mod in this file.
# Servers are automatically sorted alphabetically when shown in the list.
# This file live updates the in-game listing. Feel free to change it while in the main menu.

Bjornworld-Local:
  address: 10.0.0.16
  port: 2456
  password: Ryzen5Valheim

Resources-Local:
  address: 10.0.0.16
  port: 2466
  password: Ryzen5Valheim